### PR TITLE
Fix link to "Commandline REPL"

### PR DESCRIPTION
**Pull request by srenatus**
Not a dedicated site, but the best reference I could find... so if there's a better one, please disregard... :)

### CODE REVIEW

**Comment by DavyLandman** [comment]
Ah yes, that was an old url, thank you!

Actually we now have to links.
http://update.rascal-mpl.org/console/rascal-shell-stable.jar

and the CI build unstable versions for living on the edge:
http://update.rascal-mpl.org/console/rascal-shell-unstable.jar

If you update your commit with these links, I'll merge the pull request in one go :)

**Comment by srenatus** [comment]
Didn't want to mix it up too much ;) Thanks a lot!

Rascal is fun.

**Comment by DavyLandman** [comment]
cool, give the new REPL a try as well, it has some more REPL like features :)

but the experience inside eclipse is still the best, for now.

**Comment by srenatus** [comment]
Used github's Edit feature, so there's no lazy way to squash these. Please tell me if you do mind ;)

Thanks

**Pull request merged**
